/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_assignment;

import javax.swing.JOptionPane;

/**
 *
 * @author 5526
 */
public class AIT_ATM extends javax.swing.JFrame {
    
  
    int userBankChoice;
    String number = "";
    boolean loadAccount = false; 
    boolean transaction_withdraw = false;
    boolean transaction_deposit = false;
    
    
    //CREATING ACCOUNTS
    Saving account = new Saving();
    NetSavings account2 = new NetSavings();
    FixedAccount account3 = new FixedAccount();
    Cheque account4 = new Cheque();
    ExceptionsAccount exception = new ExceptionsAccount();
    
    //VALUES ASSIGNED TO BE CONSTANT AND NEVER BE CHANGED
    public static final int LimitOfSavingsAcc = 2000;
    public static final int LimitOfNetSavingsAcc = 1000;
    public static final int LimitOfFixedAcc = 700;
    
    public AIT_ATM() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Number3 = new javax.swing.JButton();
        balanceEnquiryButton = new javax.swing.JButton();
        Number4 = new javax.swing.JButton();
        Number0 = new javax.swing.JButton();
        Number5 = new javax.swing.JButton();
        dotButton = new javax.swing.JButton();
        Number6 = new javax.swing.JButton();
        newTransactionButton = new javax.swing.JButton();
        Number7 = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        Number8 = new javax.swing.JButton();
        enterButton = new javax.swing.JButton();
        Number9 = new javax.swing.JButton();
        withdrawButton = new javax.swing.JButton();
        depositButton = new javax.swing.JButton();
        Number2 = new javax.swing.JButton();
        Number1 = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoBox = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Number3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Number3.setText("3");
        Number3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number3ActionPerformed(evt);
            }
        });

        balanceEnquiryButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        balanceEnquiryButton.setText("Balance Enquiry");
        balanceEnquiryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceEnquiryButtonActionPerformed(evt);
            }
        });

        Number4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Number4.setText("4");
        Number4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number4ActionPerformed(evt);
            }
        });

        Number0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Number0.setText("0");
        Number0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number0ActionPerformed(evt);
            }
        });

        Number5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Number5.setText("5");
        Number5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number5ActionPerformed(evt);
            }
        });

        dotButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dotButton.setText(".");
        dotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotButtonActionPerformed(evt);
            }
        });

        Number6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Number6.setText("6");
        Number6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number6ActionPerformed(evt);
            }
        });

        newTransactionButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newTransactionButton.setText("New Transaction");
        newTransactionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTransactionButtonActionPerformed(evt);
            }
        });

        Number7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Number7.setText("7");
        Number7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number7ActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        Number8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Number8.setText("8");
        Number8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number8ActionPerformed(evt);
            }
        });

        enterButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enterButton.setText("Enter");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        Number9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Number9.setText("9");
        Number9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number9ActionPerformed(evt);
            }
        });

        withdrawButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        withdrawButton.setText("Withdraw");
        withdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawButtonActionPerformed(evt);
            }
        });

        depositButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        depositButton.setText("Deposit");
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });

        Number2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Number2.setText("2");
        Number2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number2ActionPerformed(evt);
            }
        });

        Number1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Number1.setText("1");
        Number1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number1ActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        infoBox.setColumns(20);
        infoBox.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        infoBox.setRows(5);
        infoBox.setText("Welcome to AIT Banking====\nPlease select from the following accounts:\n1-Savings\n2-NetSavings\n3-Fixed\n4-Cheque\n");
        jScrollPane1.setViewportView(infoBox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Number7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Number8, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Number9, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Number1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Number2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Number3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Number0, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Number4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Number5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Number6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(withdrawButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(newTransactionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(depositButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(balanceEnquiryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Number7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Number8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Number9, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Number4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Number5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Number6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Number1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Number2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Number3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Number0, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(balanceEnquiryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newTransactionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(withdrawButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(depositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newTransactionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTransactionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newTransactionButtonActionPerformed

    //VIEW BALANCE ENQUIRY BUTTON
    private void balanceEnquiryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceEnquiryButtonActionPerformed
        // TODO add your handling code here:
        
        //CHECK BALANCE IF
        if(loadAccount == true){
            if(userBankChoice == 1){
                infoBox.setText("Current Balance:" + Double.toString(account.current_balance));
            }else if(userBankChoice == 2){
                infoBox.setText("Current Balance:" + Double.toString(account2.current_balance));
            }else if(userBankChoice == 3){
                infoBox.setText("Current Balance:" + Double.toString(account3.current_balance));
            }else if(userBankChoice == 4){
                infoBox.setText("Current Balance:" + Double.toString(account4.current_balance));
            }else{
                JOptionPane.showMessageDialog(null," ");
            }
        }else{
           infoBox.setText("Sorry but no account has been chosen");

        }
        
    }//GEN-LAST:event_balanceEnquiryButtonActionPerformed

    //BUTTON 8
    private void Number8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number8ActionPerformed
        infoBox.append("8");
        number = number + '8';
    }//GEN-LAST:event_Number8ActionPerformed

    //BUTTON 7
    private void Number7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number7ActionPerformed
        infoBox.append("7");
        number = number + '7';
    }//GEN-LAST:event_Number7ActionPerformed

    //BUTTON 1
    private void Number1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number1ActionPerformed
        
        if (loadAccount == true){
             infoBox.append("1");
             number = number + '1';
    }        
        else{
            loadAccount = true;
            userBankChoice = 1;
            infoBox.setText("You have selected Savings Account.\nPlease choose what would you like to do:\nWithdraw\nDeposit\nBalanceEnquiry\n");
        }   
    }//GEN-LAST:event_Number1ActionPerformed

    //BUTTON 2
    private void Number2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number2ActionPerformed
       
        
         //check if account loaded
        if(loadAccount == true){
            
            
          infoBox.append("2");
          number = number + '2';
        
        //if no account is loaded
        }else{
            loadAccount = true;
            userBankChoice = 2;
            infoBox.setText("You have chosen NetSavings account.\nPlease click what would you like to do:\nWithdraw\nDeposit\nViewBalance\nhalp");

        } 
    }//GEN-LAST:event_Number2ActionPerformed
     
    //BUTTON 3
    private void Number3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number3ActionPerformed
        // TODO add your handling code here:
        
        
        if(loadAccount == true){
            //check which account
            infoBox.append("3");
        number = number + '3';
            
        
        //if no account is loaded
        }else{
            loadAccount = true;
            userBankChoice = 3;
            infoBox.setText("You have chosen Fixed Account.\nPlease click what would you like to do:\nWithdraw\nDeposit\nViewBalance\nhalp");

        }
    }//GEN-LAST:event_Number3ActionPerformed

    //BUTTON 4
    private void Number4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number4ActionPerformed
      
        
        if(loadAccount == true){
            //if statements check which account is loaded
            infoBox.append("4");
        number = number + '4';
            
        
        //if no account is loaded
        }else{
            loadAccount = true;
            userBankChoice = 4;
            infoBox.setText("You have chosen Cheque Account.\nPlease click what would you like to do:\nWithdraw\nDeposit\nViewBalance\nhalp");

        }
    }//GEN-LAST:event_Number4ActionPerformed

    //BUTTON 5
    private void Number5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number5ActionPerformed
        infoBox.append("5");
        number = number + '5';
    }//GEN-LAST:event_Number5ActionPerformed

    //BUTTON 6
    private void Number6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number6ActionPerformed
        infoBox.append("6");
        number = number + '6';
    }//GEN-LAST:event_Number6ActionPerformed

    //BUTTON 9
    private void Number9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number9ActionPerformed
        infoBox.append("9");
        number = number + '9';
    }//GEN-LAST:event_Number9ActionPerformed

    //BUTTON 0
    private void Number0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number0ActionPerformed
        infoBox.append("0");
        number = number + '0';
    }//GEN-LAST:event_Number0ActionPerformed

    private void dotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotButtonActionPerformed
        infoBox.append(".");
    }//GEN-LAST:event_dotButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        infoBox.append("");
    }//GEN-LAST:event_clearButtonActionPerformed

    //WITHDRAW BUTTON 
    private void withdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawButtonActionPerformed
        // TODO add your handling code here:
        if(loadAccount == true){
            
            transaction_withdraw = true;
            transaction_deposit = false;
                   
                infoBox.setText("Please enter amount to withdraw: ");
                
        }else{
           infoBox.setText("you haven't selected an account");

        }
    }//GEN-LAST:event_withdrawButtonActionPerformed

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        // TODO add your handling code here:
         if(transaction_withdraw){
            if(userBankChoice == 1 && exception.isWithdrawlValid(LimitOfSavingsAcc, Integer.parseInt(number), account.current_balance)){
                account.Withdraw(Integer.parseInt(number));
                infoBox.setText("You have withdrawed " + number + "\nYour current balance:" + account.current_balance);
                transaction_withdraw = false;
            }else if (userBankChoice == 2 && exception.isWithdrawlValid(LimitOfNetSavingsAcc, Integer.parseInt(number), account2.current_balance)){
                account2.Withdraw(Integer.parseInt(number));
                infoBox.setText("You have withdrawed " + number + "\nYour current balance:" + account2.current_balance);
                transaction_withdraw = false;
            }else if (userBankChoice == 3 && exception.isWithdrawlValid(LimitOfFixedAcc, Integer.parseInt(number), account3.current_balance)){
                account3.Withdraw(Integer.parseInt(number));
                infoBox.setText("You have withdrawed " + number + "\nYour current balance:" + account3.current_balance);
                transaction_withdraw = false;
            }else if (userBankChoice == 4 && exception.isWithdrawlValid(999999999, Integer.parseInt(number), account4.current_balance)){
                account4.Withdraw(Integer.parseInt(number));
                infoBox.setText("You have withdrawed " + number + "\nYour current balance:" + account4.current_balance);
                transaction_withdraw = false;
            }else{
                infoBox.setText("Please enter value again to withdraw:");
            }            
            
            
        }
        
         
         else{
            
        }
        
       number = "";
        
    }//GEN-LAST:event_enterButtonActionPerformed

    //BUTTON DEPOSIT
    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
        // TODO add your handling code here:
        
        if(loadAccount == true){
                    
            transaction_deposit = true;
            transaction_withdraw = false;
            
            infoBox.setText("Please enter amount to deposit: ");

            
        }else{
           infoBox.setText("No account has been selected");

        }
    }//GEN-LAST:event_depositButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        
       number = "";
       infoBox.setText("This action has been cancelled.");
       transaction_withdraw = false;
       transaction_deposit = false;
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AIT_ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AIT_ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AIT_ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AIT_ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AIT_ATM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Number0;
    private javax.swing.JButton Number1;
    private javax.swing.JButton Number2;
    private javax.swing.JButton Number3;
    private javax.swing.JButton Number4;
    private javax.swing.JButton Number5;
    private javax.swing.JButton Number6;
    private javax.swing.JButton Number7;
    private javax.swing.JButton Number8;
    private javax.swing.JButton Number9;
    private javax.swing.JButton balanceEnquiryButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton depositButton;
    private javax.swing.JButton dotButton;
    private javax.swing.JButton enterButton;
    private javax.swing.JTextArea infoBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newTransactionButton;
    private javax.swing.JButton withdrawButton;
    // End of variables declaration//GEN-END:variables
}
